from . import respartner
from . import crmlead
from . import whatsapp_event_type
from . import whatsapp_event
from . import whatsapp_message_layout
from . import whatsapp_message
from . import whatsapp_tag
from . import whatsapp_type_menssage
from . import whatsapp_send_menssage
from . import whatsapp_deactivation_history
from . import whatsapp_duplicate_contact_choice
from . import whatsapp_duplicate_contact_wizard