from . import res_partner
from . import informa_matricula
from . import informa_cursos
from . import informa_curriculo_variante
from . import informa_curriculo
from . import informa_disciplina
from . import registro_disciplina
from . import tipo_ingresso
from . import tipo_cancelamento
from . import matricula_status_change_wizard
from . import matricula_reingresso_wizard
from . import matricula_confirmation_wizard
